### PR TITLE
Support `effort` and deprecate `speed` option

### PR DESCRIPTION
**Pull request by kidonng**
[`speed` has been deprecated in sharp v0.30.0](https://sharp.pixelplumbing.com/changelog#v0300---1st-february-2022).

However I'm not sure about renaming the CLI option since it may be more "breaking" than the library itself. But this is up to you :)

### CODE REVIEW

**Comment by lovell** [comment]
Hello, thanks for the PR.

The value for `effort` is inversely proportional to `speed` - you can see how sharp converts from the latter to the former here:
 
https://github.com/lovell/sharp/blob/b10d8f89ca8190b3973a5c4c0e419be21eab3777/lib/output.js#L869

We should probably support both, and it looks like `yargs` has a `deprecateOption` feature we can use for this.

https://yargs.js.org/docs/#api-reference-deprecateoptionkey-msg-boolean

**Comment by kidonng** [comment]
Thanks for the helpful links! Let me know if the latest changes looks good to you :)

**Comment by lovell** [comment]
Thank you!

**Comment by lovell** [comment]
Published as v0.3.1, thanks again.

**Pull request merged**
